### ISSUE TITLE
Titles aren't showing up on firefox

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#250] opened 2021-07-14 09:51 UTC
Works on brave and safari :(

<img width="1837" alt="Screenshot 2021-07-14 at 11 50 17" src="https://user-images.githubusercontent.com/2326909/125602168-88cf6f74-4439-4b70-89a3-484f1f5a3947.png">

**Comment by brandonhaslegs** [comment] 2021-07-14 09:56
I see the title on all browsers. Looks like you just have the text selected in this screenshot.

![image](https://user-images.githubusercontent.com/4406983/125602912-67145ad4-c939-430e-b313-f0c29910f603.png)

**Comment by SNikhill** [comment] 2021-08-05 08:03
I can confirm Mr Brandon's observation. I can see titles on my Firefox instance. And that green "stuff" is from Firefox's selection overlay. (Their new theme has made it green from blue).

**Comment by SNikhill** [comment] 2021-08-29 18:58
@brandonhaslegs 

Sir, can I request a reopening of this issue? 
@juliendonck May I please know which firefox edition you were using and did you get an error in the console stating that the font was rejected by `Sanitizer`?

I wanted to visit the website for a design reference and was greeted with this (repeatedly):
![image](https://user-images.githubusercontent.com/51415616/131262181-16473fa5-36fa-469f-9ce6-28196f2e064f.png)

**Browser Used:** `Firefox Developer Edition`

And now, I understand why @juliendonck had selected the titles (The green overlay):
![image](https://user-images.githubusercontent.com/51415616/131262210-de806862-1dc8-47eb-a10b-c35f378246cf.png)

**Comment by SNikhill** [comment] 2021-08-29 19:16
@brandonhaslegs 
Sir, on another review, it is not an issue with the font since that (F) is trying to show up and if I scroll below, starting letters from other titles are partially showing up too.

This seems to be an issue with the Blending Mode. Like, the `mix-blend-mode` property.

**Comment by brandonhaslegs** [comment] 2021-08-29 19:26
Reopened, feel free to see if you can find a fix. I haven't looked at it in Developer Firefox.

**Comment by SNikhill** [comment] 2021-09-04 07:25
@brandonhaslegs 

So, you have specified a Background rather than an actual colour and then, clipping the background to just text, to achieve the desired Gradient Effect. But, turns out that the gradient you have specified is not the one you may have wanted.

From your Figma File:
- The gradient you wanted:
![image](https://user-images.githubusercontent.com/51415616/132085857-1f3cca17-d35c-4792-9d03-809d1cb30046.png)

- And the Gradient you have specified:
![image](https://user-images.githubusercontent.com/51415616/132085871-b296f86d-93e3-409b-bd3f-3626854911f9.png)

The reason this gradient is converted to the other one is that you are using `mix-blend-mode` with `exclusion`. [Which is basically what Figma showed].

If you try to disable the `mix-blend-mode`, here is the text you get:
![image](https://user-images.githubusercontent.com/51415616/132085940-3575c6bd-556d-4555-8f05-d37abbaf4cb0.png)

Now, this colour is appropriate and is what you should get since that is the actual gradient that you have specified.

Now, I tried to copy your Figma file to generate the correct gradient:
Here is [the link](https://www.figma.com/file/w2BoSLo1ruHCHfbf0W63dG/Radicle-Website-Copy?node-id=1861%3A81320)

Here is the result (From Figma File) (Gradient is close to the actual, desired gradient):
![image](https://user-images.githubusercontent.com/51415616/132086457-1080d0bf-2b16-4359-b5cb-845978ae7bbf.png)

![image](https://user-images.githubusercontent.com/51415616/132086466-3adb47a9-a9bd-454c-9f71-605305f7a7f2.png)


And here is the gradient applied in an actual firefox developer edition window:
![image](https://user-images.githubusercontent.com/51415616/132086498-9a7b8d35-50c2-452b-9197-e68d2f883499.png)


(PS: The text can be brought forward, the right way using positioning)

**Comment by SNikhill** [comment] 2021-09-04 07:27
Also, thank you @brandonhaslegs 
I am learning new stuff due to this issue. :)

**Comment by brandonhaslegs** [comment] 2021-09-04 07:28
But we want to use the mix blend mode on the titles, so the color specified has to be the _opposite_ of what color you want. This is so you get that effect of the letters overlapping the images.

**Comment by SNikhill** [comment] 2021-09-04 07:38
Yes, I got that. But, due to some issues, `exclusion` is not working on Firefox. We can still bring the text forward.

I shall explore further and let you know if I find a workaround.

**Comment by SNikhill** [comment] 2021-09-15 12:20
@brandonhaslegs 

The issue has been fixed in the latest Firefox Developer Version.
![image](https://user-images.githubusercontent.com/51415616/133432067-d89a13cf-dc91-4575-afaa-06ce9c41b019.png)

**Closed** 2021-09-15 12:47 UTC
